consulting/urls.py
from django.contrib import admin
from django.urls import path

from consulting.views import IndexView, AboutView, ContactView, ServiceView

app_name = 'consulting'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('about/', AboutView.as_view(), name='about'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('service/', ServiceView.as_view(), name='service'),
]

consulting_root/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic import TemplateView
from django.contrib.sitemaps.views import sitemap

sitemaps = {

}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('consulting.urls', namespace='consulting')),
    re_path(r'robots\.txt', TemplateView.as_view(template_name='seo/robots.txt', content_type='text/plain')),
    re_path(r'sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]

consulting/models.py
from django.db import models


# Create your models here.
class Contact(models.Model):
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Contact object {self.pk}'

consulting/forms.py
from django import forms

from consulting.models import Contact


class LetsTalkForm(forms.Form):
    name = forms.CharField(max_length=64, widget=forms.TextInput(attrs={
        'placeholder': 'Введите имя', 'class': 'form-control', 'type': 'text', 'autocomplete': 'off'
    }))
    email = forms.EmailField(widget=forms.EmailInput(attrs={
        'placeholder': 'Введите email', 'class': 'form-control', 'type': 'email', 'autocomplete': 'off'
    }))
    phone_number = forms.IntegerField(widget=forms.NumberInput(attrs={
        'placeholder': 'Введите телефон', 'class': 'form-control', 'type': 'text', 'autocomplete': 'off'
    }))

    class Meta:
        fields = ('name', 'email', 'phone_number')


class IndexForm(forms.Form):
    name = forms.CharField(max_length=64, widget=forms.TextInput(attrs={
        'placeholder': 'Введите имя', 'class': 'form-control', 'type': 'text', 'autocomplete': 'off'
    }))
    email = forms.EmailField(widget=forms.EmailInput(attrs={
        'placeholder': 'Введите email', 'class': 'form-control', 'type': 'email', 'autocomplete': 'off'
    }))
    text = forms.CharField(widget=forms.Textarea(attrs={
        'placeholder': 'Введите сообщение', 'class': 'form-control', 'type': 'text',
        'style': 'font-size: 16px;', 'autocomplete': 'off'
    }))

    class Meta:
        fields = ('name', 'email', 'text')


class ContactForm(forms.Form):
    name = forms.CharField(max_length=64, widget=forms.TextInput(attrs={
        'placeholder': 'Введите имя', 'class': 'form-control', 'type': 'text', 'autocomplete': 'off'
    }))
    email = forms.EmailField(widget=forms.EmailInput(attrs={
        'placeholder': 'Введите email', 'class': 'form-control', 'type': 'email', 'autocomplete': 'off'
    }))
    subject = forms.CharField(max_length=128, widget=forms.TextInput(attrs={
        'placeholder': 'Введите тему', 'class': 'form-control', 'type': 'text', 'autocomplete': 'off'
    }))
    text = forms.CharField(widget=forms.Textarea(attrs={
        'placeholder': 'Введите сообщение', 'class': 'form-control', 'type': 'text',
        'style': 'font-size: 16px;', 'autocomplete': 'off'
    }))

    class Meta:
        fields = ('name', 'email', 'subject', 'text')

common/views.py
from django.shortcuts import render

from consulting.forms import LetsTalkForm

from common.tasks import self_email


class CommonContextMixin:
    title = None

    def get_context_data(self, **kwargs):
        context = super(CommonContextMixin, self).get_context_data(**kwargs)
        context['title'] = self.title
        return context


class CommonFormsMixin:
    template_name = None

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['ltf'] = LetsTalkForm()
        # context['ff'] = FeedbackForm()
        # context['searchform'] = SearchbarForm()
        return context

    def post(self, request, *args, **kwargs):
        lt_form = LetsTalkForm(request.POST)

        if lt_form.is_valid():
            name = lt_form.cleaned_data['name']
            email = lt_form.cleaned_data['email']
            phone = lt_form.cleaned_data['phone_number']

            message = f'\nОтправитель: {name} \n\nEmail: {email} \n\nPhone: {phone} \n\n'
            self_email.delay('Let\'s Talk', message)

        context = self.get_context_data(**kwargs)
        context['ltf'] = LetsTalkForm()

        return render(request, self.template_name, context)

consulting/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

from common.views import CommonContextMixin, CommonFormsMixin
from consulting.forms import IndexForm, LetsTalkForm, ContactForm

from common.tasks import self_email

pages = ['Домой', 'О нас', 'Услуги', 'Контакты']


class IndexView(CommonContextMixin, TemplateView):
    template_name = 'consulting/index.html'
    title = 'Академ-аудит - Домой'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['index_view'] = 'index_view'

        page_list = pages.copy()
        page_list.remove('Домой')
        context['page_list'] = page_list

        i_form = IndexForm()
        lt_form = LetsTalkForm()
        context['if'] = i_form
        context['ltf'] = lt_form
        return context

    def post(self, request, *args, **kwargs):
        i_form = IndexForm(request.POST)
        lt_form = LetsTalkForm(request.POST)

        if i_form.is_valid():
            name = i_form.cleaned_data['name']
            email = i_form.cleaned_data['email']
            phone = i_form.cleaned_data['text']

            message = f'\nОтправитель: {name} \n\nEmail: {email} \n\nText: {phone} \n\n'
            self_email.delay('Home page', message)

        if lt_form.is_valid():
            name = lt_form.cleaned_data['name']
            email = lt_form.cleaned_data['email']
            phone = lt_form.cleaned_data['phone_number']

            message = f'\nОтправитель: {name} \n\nEmail: {email} \n\nPhone: {phone} \n\n'
            self_email.delay('Let\'s Talk', message)

        context = self.get_context_data(**kwargs)
        context['if'] = IndexForm()
        context['ltf'] = LetsTalkForm()

        return render(request, self.template_name, context)


class AboutView(CommonContextMixin, CommonFormsMixin, TemplateView):
    template_name = 'consulting/about.html'
    title = 'Академ-аудит - О нас'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['about_view'] = 'about_view'

        page_list = pages.copy()
        page_list.remove('О нас')
        context['page_list'] = page_list

        return context


class ContactView(CommonContextMixin, CommonFormsMixin, TemplateView):
    template_name = 'consulting/contact.html'
    title = 'Академ-аудит - Контакты'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['contact_view'] = 'contact_view'

        page_list = pages.copy()
        page_list.remove('Контакты')
        context['page_list'] = page_list

        contact_form = ContactForm()
        lt_form = LetsTalkForm()
        context['cf'] = contact_form
        context['ltf'] = lt_form

        return context

    def post(self, request, *args, **kwargs):
        contact_form = ContactForm(request.POST)
        lt_form = LetsTalkForm(request.POST)

        if contact_form.is_valid():
            name = contact_form.cleaned_data['name']
            email = contact_form.cleaned_data['email']
            subject = contact_form.cleaned_data['subject']
            msg = contact_form.cleaned_data['text']

            message = f'\nОтправитель: {name} \n\nEmail: {email} \n\nMessage: {msg} \n\n'
            self_email.delay('Home page', message, subject=subject)

        if lt_form.is_valid():
            name = lt_form.cleaned_data['name']
            email = lt_form.cleaned_data['email']
            phone = lt_form.cleaned_data['phone_number']

            message = f'\nОтправитель: {name} \n\nEmail: {email} \n\nPhone: {phone} \n\n'
            self_email.delay('Let\'s Talk', message)

        context = self.get_context_data(**kwargs)
        context['cf'] = ContactForm()
        context['ltf'] = LetsTalkForm()

        return render(request, self.template_name, context)


class ServiceView(CommonContextMixin, CommonFormsMixin, TemplateView):
    template_name = 'consulting/service.html'
    title = 'Академ-аудит - Услуги'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['service_view'] = 'service_view'

        page_list = pages.copy()
        page_list.remove('Услуги')
        context['page_list'] = page_list

        return context

consulting/templates/consulting/clients.html
{% load static %}

<!-- our brand area start -->
    <div class="rts-brand-area rts-section-gapBottom" style="margin-top: 20px;">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="brand-one-wrapper">
                        <!-- Swiper -->
                        <div class="swiper brand-1">
                            <div class="swiper-wrapper">
                                <div class="swiper-slide">
                                    <a href="#"><img src="{% static 'assets/images/clients/amsel_svyaz.jpg' %}" alt="Brand_area_images"></a>
                                </div>
                                <div class="swiper-slide">
                                    <a href="#"><img src="{% static 'assets/images/clients/amtel_service.jpg' %}" alt="Brand_area_images"></a>
                                </div>
                                <div class="swiper-slide">
                                    <a href="#"><img src="{% static 'assets/images/clients/farm.jpg' %}" alt="Brand_area_images"></a>
                                </div>
                                <div class="swiper-slide">
                                    <a href="#"><img src="{% static 'assets/images/clients/kenmer.png' %}" alt="Brand_area_images"></a>
                                </div>
                                <div class="swiper-slide">
                                    <a href="#"><img class="mt-dec-brand" src="{% static 'assets/images/clients/kenmer.jpeg' %}" alt="Brand_area_images"></a>
                                </div>
                                <div class="swiper-slide">
                                    <a href="#"><img src="{% static 'assets/images/clients/logo-pobeda-1.jpg' %}" alt="Brand_area_images"></a>
                                </div>
                                <div class="swiper-slide">
                                    <a href="#"><img src="{% static 'assets/images/clients/mdm.png' %}" alt="Brand_area_images"></a>
                                </div>
                                <div class="swiper-slide">
                                    <a href="#"><img src="{% static 'assets/images/clients/mosfilm.png' %}" style="width: 150px; height:400px;" alt="Brand_area_images"></a>
                                </div>
                                <div class="swiper-slide">
                                    <a href="#"><img src="{% static 'assets/images/clients/termotex.png' %}" alt="Brand_area_images"></a>
                                </div>
                                <div class="swiper-slide">
                                    <a href="#"><img class="mt-dec-brand" src="{% static 'assets/images/clients/vertical.jpg' %}" alt="Brand_area_images"></a>
                                </div>
                                <div class="swiper-slide">
                                    <a href="#"><img class="mt-dec-brand" src="{% static 'assets/images/clients/WIELTON.jpg' %}" alt="Brand_area_images"></a>
                                </div>
                            </div>
                        </div>
                        <!-- swiper end -->
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- our brand area End -->

consulting/templates/consulting/contact.html
{% extends 'consulting/base.html' %}

{% load static %}

{% block content %}

<!-- start breadcrumb area -->
    <div class="rts-breadcrumb-area breadcrumb-bg bg_image">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12 breadcrumb-1">
                    <h1 class="title" style="font-size: 60px;" data-sal-delay="150" data-sal="slide-up" data-sal-duration="800">Контакты</h1>
                </div>
                <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12">
                    <div class="bread-tag">
                        <a href="{% url 'consulting:index' %}" data-sal-delay="250" data-sal="slide-up" data-sal-duration="800">Домой</a>
                        <span> / </span>
                        <a href="#" class="active" data-sal-delay="450" data-sal="slide-up" data-sal-duration="800">Контакты</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- end breadcrumb area -->


    <!-- contact single area start -->
    <div class="rts-contact-area-page rts-section-gap">
        <div class="container">
            <div class="row g-5">
                <!-- single contact area -->
                <div class="col-xl-4 col-lg-4 col-md-6 col-sm-6 col-12">
                    <div class="single-contact-one-inner sal-animate" data-sal-delay="150" data-sal="slide-up" data-sal-duration="800">
                        <div class="thumbnail">
<!--                            <img src="{% static 'assets/images/contact/01.png' %}" alt="">-->
                        </div>
                        <div class="content">
                            <div class="icone">
                                <img src="{% static 'assets/images/contact/shape/01.svg' %}" alt="">
                            </div>
                            <div class="info">
                                <span>Мобильный номер:</span>
                                <a href="tel:+18475555555">
                                    <h5>8 (495) 504-86-40</h5>
                                    <h5>8 (903) 281-04-20</h5>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- single contact area end -->
                <!-- single contact area -->
                <div class="col-xl-4 col-lg-4 col-md-6 col-sm-6 col-12">
                    <div class="single-contact-one-inner sal-animate" data-sal-delay="200" data-sal="slide-up" data-sal-duration="800">
                        <div class="thumbnail">
<!--                            <img src="{% static 'assets/images/contact/02.png' %}" alt="">-->
                        </div>
                        <div class="content">
                            <div class="icone">
                                <img src="{% static 'assets/images/contact/shape/02.svg' %}" alt="">
                            </div>
                            <div class="info">
                                <span>Ваши предложения:</span>
                                <a href="#">
                                    <h5>info@akfakademaudit.com</h5>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- single contact area end -->
                <!-- single contact area -->
                <div class="col-xl-4 col-lg-4 col-md-6 col-sm-6 col-12">
                    <div class="single-contact-one-inner sal-animate" data-sal-delay="350" data-sal="slide-up" data-sal-duration="800">
                        <div class="thumbnail">
<!--                            <img src="{% static 'assets/images/contact/03.png' %}" alt="">-->
                        </div>
                        <div class="content">
                            <div class="icone">
                                <img src="{% static 'assets/images/contact/shape/03.svg' %}" alt="">
                            </div>
                            <div class="info">
                                <span>Адрес компании:</span>
                                <a href="#">
                                    <h5>г.Москва, ул. Коштоянца, д.10</h5>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- single contact area end -->
            </div>
        </div>
    </div>
    <!-- conact single area end -->

    <!-- conact us form fluid start -->
    <div class="rts-contact-form-area">
        <div class="container">
            <div class="rts-contact-fluid rts-section-gap">
                <div class="row mb--30">
                    <div class="col-12">
                        <div class="title-area text-center">
                            <span data-sal-delay="150" data-sal="slide-up" data-sal-duration="800"
                                class="sal-animate">Связаться</span>
                            <h2 class="title animated fadeIn sal-animate"  style="font-size: 34px;" data-sal-delay="250" data-sal="slide-up" data-sal-duration="800">Оставьте свои комментарии о работе нашей компании
                            </h2>
                        </div>
                    </div>
                </div>
                <div class="form-wrapper">
                    <div id="form-messages"></div>
                    <form id="cf" action="{% url 'consulting:contact' %}" method="post">
                        {% csrf_token %}
                        <div class="name-email">
<!--                            <input type="text" name="name" placeholder="Your Name" required>-->
<!--                            <input type="email" name="email" placeholder="Email Address" required>-->
                            {{ cf.name }}
                            {{ cf.email }}
                        </div>
<!--                        <input type="text" name="subject" placeholder="Your Subject">-->
                        {{ cf.subject }}
<!--                        <textarea placeholder="Type Your Message" name="message"></textarea>-->
                        {{ cf.text }}
                        <button type="submit" class="rts-btn btn-primary" form="cf">Отправить</button>
                    </form>
                </div>
            </div>
        </div>

    </div>
    <!-- conact us form fluid end -->

    <!-- start Footer area -->

<!--    &lt;!&ndash; our brand area style two &ndash;&gt;-->
<!--    <div class="rts-brand-area bg_brand&#45;&#45;two ptb&#45;&#45;100">-->
<!--        <div class="container">-->
<!--            <div class="row">-->
<!--                <div class="col-12">-->
<!--                    <div class="brand-wrapper-two">-->
<!--                        &lt;!&ndash; Swiper &ndash;&gt;-->
<!--                        <div class="swiper brand-1">-->
<!--                            <div class="swiper-wrapper">-->
<!--                                <div class="swiper-slide">-->
<!--                                    <a href="#"><img src="assets/images/brand/06.png" alt="Brand_area_images"></a>-->
<!--                                </div>-->
<!--                                <div class="swiper-slide">-->
<!--                                    <a href="#"><img src="assets/images/brand/07.png" alt="Brand_area_images"></a>-->
<!--                                </div>-->
<!--                                <div class="swiper-slide">-->
<!--                                    <a href="#"><img src="assets/images/brand/08.png" alt="Brand_area_images"></a>-->
<!--                                </div>-->
<!--                                <div class="swiper-slide">-->
<!--                                    <a href="#"><img src="assets/images/brand/09.png" alt="Brand_area_images"></a>-->
<!--                                </div>-->
<!--                                <div class="swiper-slide">-->
<!--                                    <a href="#"><img class="mt-dec-brand" src="assets/images/brand/10.png" alt="Brand_area_images"></a>-->
<!--                                </div>-->
<!--                                <div class="swiper-slide">-->
<!--                                    <a href="#"><img src="assets/images/brand/06.png" alt="Brand_area_images"></a>-->
<!--                                </div>-->
<!--                                <div class="swiper-slide">-->
<!--                                    <a href="#"><img src="assets/images/brand/07.png" alt="Brand_area_images"></a>-->
<!--                                </div>-->
<!--                                <div class="swiper-slide">-->
<!--                                    <a href="#"><img src="assets/images/brand/08.png" alt="Brand_area_images"></a>-->
<!--                                </div>-->
<!--                                <div class="swiper-slide">-->
<!--                                    <a href="#"><img src="assets/images/brand/09.png" alt="Brand_area_images"></a>-->
<!--                                </div>-->
<!--                                <div class="swiper-slide">-->
<!--                                    <a href="#"><img class="mt-dec-brand" src="assets/images/brand/10.png" alt="Brand_area_images"></a>-->
<!--                                </div>-->
<!--                            </div>-->
<!--                        </div>-->
<!--                        &lt;!&ndash; swiper end &ndash;&gt;-->
<!--                    </div>-->
<!--                </div>-->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->
<!--    &lt;!&ndash; our brand area style two End &ndash;&gt;-->
{% include 'consulting/clients.html' %}
    <!-- ENd Footer Area -->
{% endblock %}